import React, { useState, useEffect } from 'react';
import { X, Copy, Download, RefreshCw, AlertCircle, FileText, Loader2 } from 'lucide-react';
import { repositoryApi } from '../../shared/api';
import { useToast } from '../../shared/context/ToastContext';

export default function ADRPanel({ repoId, risk, onClose }) {
  const [adr, setAdr] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const { addToast } = useToast();

  const generate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await repositoryApi.generateADR(repoId, risk);
      setAdr(res.data);
    } catch (err) {
      setError(err.message || 'Failed to generate ADR');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (risk && !adr && !loading && !error) {
      generate();
    }
  }, [risk]);

  const handleChange = (field, value) => {
    setAdr(prev => ({ ...prev, [field]: value }));
  };

  const getMarkdown = () => {
    if (!adr) return '';
    return `# ADR: ${adr.title}
    
## Status
${adr.status}

## Context
${adr.context}

## Decision
${adr.decision}

## Consequences
${adr.consequences}

## Alternatives
${adr.alternatives}

## Evidence
${adr.evidence}

---
*Generated by CodeLens on ${adr.date}*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getMarkdown());
    addToast({ title: 'Copied', description: 'ADR copied to clipboard', type: 'success' });
  };

  const handleDownload = () => {
    const blob = new Blob([getMarkdown()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `adr-${adr.id.substring(0,8)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!risk) return null;

  return (
    <div className="fixed inset-y-0 right-0 w-[600px] max-w-[90vw] bg-surface border-l border-border shadow-2xl z-50 flex flex-col transform transition-transform duration-300">
      <div className="px-6 py-4 border-b border-border flex items-center justify-between shrink-0 bg-panel">
        <div className="flex items-center gap-3">
          <FileText className="w-5 h-5 text-accent" />
          <h2 className="text-lg font-semibold text-text">Draft Architecture Decision Record</h2>
        </div>
        <button onClick={onClose} className="p-2 text-muted hover:text-text rounded-md hover:bg-surface transition-colors">
          <X className="w-5 h-5" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 custom-scrollbar bg-surface/50">
        {loading ? (
          <div className="h-full flex flex-col items-center justify-center text-muted">
            <Loader2 className="w-8 h-8 animate-spin mb-4 text-accent" />
            <p>Generating ADR context with AI...</p>
          </div>
        ) : error ? (
          <div className="flex flex-col items-center justify-center p-6 bg-danger/10 border border-danger/30 rounded-lg text-danger">
            <AlertCircle className="w-8 h-8 mb-2" />
            <span className="font-semibold mb-2">Generation Failed</span>
            <p className="text-sm text-center mb-4">{error}</p>
            <button onClick={generate} className="px-4 py-2 bg-danger/20 hover:bg-danger/30 rounded transition-colors text-sm flex items-center gap-2">
              <RefreshCw className="w-4 h-4" /> Retry
            </button>
          </div>
        ) : adr ? (
          <div className="flex flex-col gap-5">
            <div>
              <label className="block text-xs font-medium text-muted uppercase tracking-wider mb-1">Title</label>
              <input 
                value={adr.title || ''} 
                onChange={(e) => handleChange('title', e.target.value)}
                className="w-full bg-panel border border-border rounded-md px-3 py-2 text-sm text-text focus:outline-none focus:border-accent"
              />
            </div>
            
            <div>
              <label className="block text-xs font-medium text-muted uppercase tracking-wider mb-1">Status</label>
              <select
                value={adr.status || 'Proposed'}
                onChange={(e) => handleChange('status', e.target.value)}
                className="w-full bg-panel border border-border rounded-md px-3 py-2 text-sm text-text focus:outline-none focus:border-accent"
              >
                <option value="Proposed">Proposed</option>
                <option value="Accepted">Accepted</option>
                <option value="Rejected">Rejected</option>
                <option value="Deprecated">Deprecated</option>
                <option value="Superseded">Superseded</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-medium text-muted uppercase tracking-wider mb-1">Context</label>
              <textarea 
                value={adr.context || ''} 
                onChange={(e) => handleChange('context', e.target.value)}
                rows={4}
                className="w-full bg-panel border border-border rounded-md px-3 py-2 text-sm text-text focus:outline-none focus:border-accent custom-scrollbar"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-muted uppercase tracking-wider mb-1">Decision</label>
              <textarea 
                value={adr.decision || ''} 
                onChange={(e) => handleChange('decision', e.target.value)}
                rows={3}
                className="w-full bg-panel border border-border rounded-md px-3 py-2 text-sm text-text focus:outline-none focus:border-accent custom-scrollbar"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-muted uppercase tracking-wider mb-1">Consequences</label>
              <textarea 
                value={adr.consequences || ''} 
                onChange={(e) => handleChange('consequences', e.target.value)}
                rows={4}
                className="w-full bg-panel border border-border rounded-md px-3 py-2 text-sm text-text focus:outline-none focus:border-accent custom-scrollbar"
              />
            </div>
            
            <div>
              <label className="block text-xs font-medium text-muted uppercase tracking-wider mb-1">Alternatives</label>
              <textarea 
                value={adr.alternatives || ''} 
                onChange={(e) => handleChange('alternatives', e.target.value)}
                rows={3}
                className="w-full bg-panel border border-border rounded-md px-3 py-2 text-sm text-text focus:outline-none focus:border-accent custom-scrollbar"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-muted uppercase tracking-wider mb-1">Evidence</label>
              <textarea 
                value={adr.evidence || ''} 
                onChange={(e) => handleChange('evidence', e.target.value)}
                rows={2}
                className="w-full bg-panel border border-border rounded-md px-3 py-2 text-sm text-text focus:outline-none focus:border-accent custom-scrollbar text-muted"
              />
            </div>
          </div>
        ) : null}
      </div>

      <div className="px-6 py-4 border-t border-border flex items-center justify-between shrink-0 bg-panel">
        <button 
          onClick={generate} 
          disabled={loading || !adr}
          className="px-3 py-1.5 text-xs font-medium text-muted hover:text-text flex items-center gap-2 transition-colors disabled:opacity-50"
        >
          <RefreshCw className="w-3.5 h-3.5" /> Regenerate
        </button>
        
        <div className="flex items-center gap-3">
          <button 
            onClick={handleCopy}
            disabled={loading || !adr}
            className="px-4 py-2 bg-surface border border-border hover:bg-surface/80 rounded-md text-sm font-medium transition-colors disabled:opacity-50 flex items-center gap-2"
          >
            <Copy className="w-4 h-4" /> Copy Markdown
          </button>
          <button 
            onClick={handleDownload}
            disabled={loading || !adr}
            className="px-4 py-2 bg-accent hover:bg-accent-hover text-white rounded-md text-sm font-medium transition-colors disabled:opacity-50 flex items-center gap-2"
          >
            <Download className="w-4 h-4" /> Download .md
          </button>
        </div>
      </div>
    </div>
  );
}
